from io import BytesIO
from datetime import datetime
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from app.models.po import PurchaseOrder
from app.models.quote import Quote
from app.models.supplier import Supplier
from app.models.company import Company


def generate_purchase_order_pdf(db, po_id: str) -> bytes:
    po: Optional[PurchaseOrder] = db.get(PurchaseOrder, po_id)
    if not po:
        raise RuntimeError("Purchase order not found")

    quote: Optional[Quote] = db.get(Quote, po.quote_id) if getattr(po, "quote_id", None) else None
    supplier: Optional[Supplier] = db.get(Supplier, po.supplier_id) if getattr(po, "supplier_id", None) else None
    company: Optional[Company] = db.get(Company, po.company_id) if getattr(po, "company_id", None) else None

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Small', fontSize=9))
    title_style = styles['Title']
    normal = styles['Normal']

    elements = []

    # Header
    company_name = company.name if company else "Procura AI"
    elements.append(Paragraph(company_name, title_style))
    elements.append(Spacer(1, 6))

    # PO metadata
    created_at = getattr(po, 'created_at', None) or datetime.utcnow()
    meta_data = [
        ["PO ID:", po.id],
        ["Date:", created_at.strftime("%Y-%m-%d")],
        ["Supplier:", supplier.name if supplier else ""],
        ["Supplier site:", supplier.website if supplier else ""],
        ["Status:", po.status or ""],
    ]
    meta_table = Table(meta_data, colWidths=[40 * mm, 120 * mm])
    meta_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 12))

    # Line items
    items = [["Item", "Qty", "Unit price", "Total"]]
    items.append([
        po.product_name or (quote.product_name if quote else ""),
        str(po.quantity),
        f"{po.unit_price:,.2f} {po.currency}",
        f"{po.total_amount:,.2f} {po.currency}",
    ])
    items_table = Table(items, colWidths=[80 * mm, 25 * mm, 40 * mm, 40 * mm])
    items_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(items_table)
    elements.append(Spacer(1, 12))

    # Totals
    total_data = [["Subtotal:", f"{po.total_amount:,.2f} {po.currency}"]]
    total_table = Table(total_data, colWidths=[145 * mm, 40 * mm])
    total_table.setStyle(TableStyle([("ALIGN", (1, 0), (-1, -1), "RIGHT")]))
    elements.append(total_table)
    elements.append(Spacer(1, 12))

    # Notes
    if getattr(po, 'notes', None):
        elements.append(Paragraph("<b>Notes:</b>", normal))
        elements.append(Paragraph(po.notes, styles['Small']))
        elements.append(Spacer(1, 12))

    elements.append(Paragraph("Authorized signature: ____________________", normal))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("This PO is generated by Procura AI. Please reference the Purchase Order ID in supplier correspondence.", styles['Italic']))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
